### ISSUE TITLE
Fix image section hero

### ISSUE THREAD

**Issue by hoanganhcs** [hoanganh20012001/easy-bank#1]

**Comment by hoanganhcs** [comment]
Deploy preview error
![image](https://user-images.githubusercontent.com/64738503/173213241-0092fa73-f7b2-4115-b25e-a6b19652d5ac.png)

**Comment by hoanganhnh** [comment]
Ok, I'm checking

**Comment by hoanganhnh** [comment]
fixed
![image](https://user-images.githubusercontent.com/75961695/173213538-0ec77e39-9898-48e1-8a08-87a9c449567d.png)

**Comment by hoanganhcs** [comment]
> fixed ![image](https://user-images.githubusercontent.com/75961695/173213538-0ec77e39-9898-48e1-8a08-87a9c449567d.png)

good

**Comment by hoanganhcs** [comment]
# It's ok

**Comment by hoanganhnh** [comment]
> # It's ok

Thanks
